//! This file has been automatically generated by `objc2`'s `header-translator`.
//! Copied from objc2-web-kit, and modified for iOS.

#![allow(non_upper_case_globals, non_snake_case)]

use objc2::__framework_prelude::*;
use objc2_core_foundation::*;
use objc2_foundation::*;
use objc2_ui_kit::*;
use objc2_web_kit::*;

extern_class!(
    /// [Apple's documentation](https://developer.apple.com/documentation/webkit/wkwebview?language=objc)
    #[unsafe(super(UIView, UIResponder, NSObject))]
    #[thread_kind = MainThreadOnly]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct WKWebView;
);

extern_conformance!(
    unsafe impl NSCoding for WKWebView {}
);

extern_conformance!(
    unsafe impl NSObjectProtocol for WKWebView {}
);

impl WKWebView {
    extern_methods!(
        /// A copy of the configuration with which the web view was
        /// initialized.
        #[unsafe(method(configuration))]
        #[unsafe(method_family = none)]
        pub unsafe fn configuration(&self) -> Retained<WKWebViewConfiguration>;

        /// The web view's navigation delegate.
        #[unsafe(method(navigationDelegate))]
        #[unsafe(method_family = none)]
        pub unsafe fn navigationDelegate(
            &self,
        ) -> Option<Retained<ProtocolObject<dyn WKNavigationDelegate>>>;

        /// Setter for [`navigationDelegate`][Self::navigationDelegate].
        ///
        /// This is a [weak property][objc2::topics::weak_property].
        #[unsafe(method(setNavigationDelegate:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setNavigationDelegate(
            &self,
            navigation_delegate: Option<&ProtocolObject<dyn WKNavigationDelegate>>,
        );

        /// Returns a web view initialized with a specified frame and
        /// configuration.
        ///
        /// Parameter `frame`: The frame for the new web view.
        ///
        /// Parameter `configuration`: The configuration for the new web view.
        ///
        /// Returns: An initialized web view, or nil if the object could not be
        /// initialized.
        ///
        /// This is a designated initializer. You can use
        ///
        /// ```text
        ///  -initWithFrame:
        /// ```
        ///
        /// to initialize an instance with the default
        /// configuration. The initializer copies the specified configuration,
        /// so mutating the configuration after invoking the initializer
        /// has no effect on the web view.
        #[unsafe(method(initWithFrame:configuration:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithFrame_configuration(
            this: Allocated<Self>,
            frame: CGRect,
            configuration: &WKWebViewConfiguration,
        ) -> Retained<Self>;

        /// Navigates to a requested URL.
        ///
        /// Parameter `request`: The request specifying the URL to which to
        /// navigate.
        ///
        /// Returns: A new navigation for the given request.
        #[unsafe(method(loadRequest:))]
        #[unsafe(method_family = none)]
        pub unsafe fn loadRequest(&self, request: &NSURLRequest) -> Option<Retained<WKNavigation>>;

        /// Sets the webpage contents and base URL.
        ///
        /// Parameter `string`: The string to use as the contents of the
        /// webpage.
        ///
        /// Parameter `baseURL`: A URL that is used to resolve relative URLs
        /// within the document.
        ///
        /// Returns: A new navigation.
        #[unsafe(method(loadHTMLString:baseURL:))]
        #[unsafe(method_family = none)]
        pub unsafe fn loadHTMLString_baseURL(
            &self,
            string: &NSString,
            base_url: Option<&NSURL>,
        ) -> Option<Retained<WKNavigation>>;

        /// The page title.
        ///
        ///
        /// ```text
        ///  WKWebView
        /// ```
        ///
        /// is key-value observing (KVO) compliant
        /// for this property.
        #[unsafe(method(title))]
        #[unsafe(method_family = none)]
        pub unsafe fn title(&self) -> Option<Retained<NSString>>;

        /// The active URL.
        ///
        /// This is the URL that should be reflected in the user
        /// interface.
        ///
        /// ```text
        ///  WKWebView
        /// ```
        ///
        /// is key-value observing (KVO) compliant for this
        /// property.
        #[unsafe(method(URL))]
        #[unsafe(method_family = none)]
        pub unsafe fn URL(&self) -> Option<Retained<NSURL>>;

        /// A Boolean value indicating whether the view is currently
        /// loading content.
        ///
        ///
        /// ```text
        ///  WKWebView
        /// ```
        ///
        /// is key-value observing (KVO) compliant
        /// for this property.
        #[unsafe(method(isLoading))]
        #[unsafe(method_family = none)]
        pub unsafe fn isLoading(&self) -> bool;

        /// A Boolean value indicating whether there is a back item in
        /// the back-forward list that can be navigated to.
        ///
        ///
        /// ```text
        ///  WKWebView
        /// ```
        ///
        /// is key-value observing (KVO) compliant
        /// for this property.
        ///
        /// See also: backForwardList.
        #[unsafe(method(canGoBack))]
        #[unsafe(method_family = none)]
        pub unsafe fn canGoBack(&self) -> bool;

        /// A Boolean value indicating whether there is a forward item in
        /// the back-forward list that can be navigated to.
        ///
        ///
        /// ```text
        ///  WKWebView
        /// ```
        ///
        /// is key-value observing (KVO) compliant
        /// for this property.
        ///
        /// See also: backForwardList.
        #[unsafe(method(canGoForward))]
        #[unsafe(method_family = none)]
        pub unsafe fn canGoForward(&self) -> bool;

        /// Navigates to the back item in the back-forward list.
        ///
        /// Returns: A new navigation to the requested item, or nil if there is
        /// no back item in the back-forward list.
        #[unsafe(method(goBack))]
        #[unsafe(method_family = none)]
        pub unsafe fn goBack(&self) -> Option<Retained<WKNavigation>>;

        /// Navigates to the forward item in the back-forward list.
        ///
        /// Returns: A new navigation to the requested item, or nil if there is
        /// no forward item in the back-forward list.
        #[unsafe(method(goForward))]
        #[unsafe(method_family = none)]
        pub unsafe fn goForward(&self) -> Option<Retained<WKNavigation>>;

        /// Reloads the current page.
        ///
        /// Returns: A new navigation representing the reload.
        #[unsafe(method(reload))]
        #[unsafe(method_family = none)]
        pub unsafe fn reload(&self) -> Option<Retained<WKNavigation>>;

        /// Reloads the current page, performing end-to-end revalidation
        /// using cache-validating conditionals if possible.
        ///
        /// Returns: A new navigation representing the reload.
        #[unsafe(method(reloadFromOrigin))]
        #[unsafe(method_family = none)]
        pub unsafe fn reloadFromOrigin(&self) -> Option<Retained<WKNavigation>>;

        /// Stops loading all resources on the current page.
        #[unsafe(method(stopLoading))]
        #[unsafe(method_family = none)]
        pub unsafe fn stopLoading(&self);
    );
}
