[package]
name = "winio-callback"
version = "0.1.1"
description = "Callback helper for winio."
edition = { workspace = true }
authors = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
