name: Winio Widgets Gallery Build

on:
  workflow_dispatch:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  windows:
    uses: ./.github/workflows/ci_release_windows.yaml

  macos:
    uses: ./.github/workflows/ci_release_macos.yaml

  linux:
    uses: ./.github/workflows/ci_release_linux.yaml

  android:
    uses: ./.github/workflows/ci_release_android.yaml
    secrets:
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

  release:
    needs:
      - windows
      - macos
      - linux
      - android

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v8
        with:
          path: artifacts

      - id: version
        run: |
          echo "version=$(grep -m1 '^version' winio/Cargo.toml | cut -d '"' -f 2)" >> $GITHUB_OUTPUT

      - uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ steps.version.outputs.version }}
          files: artifacts/**/*
          overwrite_files: true
