name: Release WinUI

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./winio-example

    strategy:
      matrix:
        include:
          - artifact: winio-exapmle-winui-x86_64.exe
            target: x86_64-pc-windows-msvc

          - artifact: winio-exapmle-winui-arm64.exe
            target: aarch64-pc-windows-msvc

    name: ${{ matrix.artifact }}

    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.target }}

      - name: Build
        shell: bash
        run: |
          cargo build \
            --release \
            --features all,nightly,windows-dark-mode,winui,winui-enable-cbs,winui-webview-system,winui-content-dialog,enable_log \
            --no-default-features \
            --target ${{ matrix.target }}

      - name: Collect
        shell: bash
        run: |
          mkdir dist

          BIN=winio-example.exe

          cp \
            "target/${{ matrix.target }}/release/${BIN}" \
            "dist/${{ matrix.artifact }}"

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact }}
          path: dist/*
